dbt_taxi_data:
  outputs:
    dev:
      dataset: taxi_trips_dataset
      job_execution_timeout_seconds: 150
      job_retries: 1
      keyfile: /home/msgrace/workspace/dev-space/de-project/chicago-taxi-trip/analytics-1/time-dotcom/config/gcp-devspace-coder-0a69080761c5.json
      location: US
      method: service-account
      priority: interactive
      project: gcp-devspace-coder
      threads: 2
      type: bigquery
  target: dev
