dbt_taxi_data:
  outputs:
    dev:
      dataset: taxi_trips_dataset
      job_execution_timeout_seconds: 150
      job_retries: 1
      keyfile: /usr/app/keys/gcp-service-account.json
      location: US
      method: service-account
      priority: interactive
      project: gcp-devspace-coder
      threads: 2
      type: bigquery
  target: dev
