dbt_taxi_data:
  outputs:
    dev:
      dataset: taxi_trips_dataset
      job_execution_timeout_seconds: 150
      job_retries: 1
      keyfile: D:\mohan\codings\devspace\analytics2\config\gcp-devspace-coder-0a69080761c5.json
      location: US
      method: service-account
      priority: interactive
      project: gcp-devspace-coder
      threads: 2
      type: bigquery
  target: dev
