services:
  postgresdb:
    container_name: postgresql-db
    image: postgres:14.17
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - api-networks

  airflow-webserver:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: airflow-container
    image: apache/airflow:3.0.0-python3.12
    ports:
      - 8000:8080
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:  
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./venv:/opt/venv
    depends_on:
      - postgresdb
    command: >
      bash -c "airflow db migrate && airflow standalone"
    networks:
      - api-networks

networks:
  api-networks:
    driver: bridge