
models:
  - name: top_tip_earners
    description: "Top 100 taxi drivers by tips earned in last 3 months"
    columns:
      - name: taxi_id
        description: "Taxi driver identifier"
        tests:
          - not_null
      - name: total_tips
        description: "Total tips earned in period"
        tests:
          - not_null
      - name: total_trips
        description: "Number of trips in period"
        tests:
          - not_null
      - name: avg_tip_per_trip
        description: "Average tip per trip"
        tests:
          - not_null
      - name: tip_earner_rank
        description: "Ranking by total tips"
        tests:
          - not_null

  - name: top_overworkers
    description: "Top 100 drivers working longest hours with insufficient breaks"
    columns:
      - name: taxi_id
        description: "Taxi driver identifier"
        tests:
          - not_null
      - name: total_shifts
        description: "Number of shifts worked"
        tests:
          - not_null
      - name: avg_shift_hours
        description: "Average shift length in hours"
        tests:
          - not_null
      - name: total_insufficient_breaks
        description: "Count of breaks less than 8 hours"
        tests:
          - not_null
      - name: overworker_rank
        description: "Ranking by total hours worked"
        tests:
          - not_null
